scyllaridae_version_tag: 5.0.2
scyllaridae_checksum: "sha256:67e7e4907a1ff79b170b558468d1a2dd95a07b80fa33ce6f832775468e07b1de" 

scyllaridae_install_dir: /opt/scyllaridae
scyllaridae_log_directory: /var/log/islandora
